--- 
- name: "my fail playbook"
  hosts: all
  
  tasks: 
    - name: "Print Hello!!"
      debug: 
        msg: "Hello from first task. Host: {{ ansible_ssh_host }}"
      failed_when: ansible_ssh_host == "127.0.0.1"
 