--- 
- name: "my first play"
  hosts: all
  
  tasks: 
    - name: "task 1 play 1"
      pause:
        seconds: 10
    - name: "task 2 play 1"
      pause:
        seconds: 10
    - name: "task 3 play 1"
      pause:
        seconds: 10
    - debug:
        msg: "play 1 summary data:\ndata\ndata\ndata\ndata\ndata"

- name: "my second play"
  hosts: all
  
  tasks: 
    - name: "task 1 play 2"
      pause:
        seconds: 10
    - name: "task 2 play 2"
      pause:
        seconds: 10
    - name: "task 3 play 2"
      pause:
        seconds: 10
    - debug:
        msg: "play 1 summary data:\ndata\ndata\ndata\ndata\ndata"

- name: "my third play"
  hosts: all
  
  tasks: 
    - name: "task 1 play 3"
      pause:
        seconds: 10
    - name: "task 2 play 3"
      pause:
        seconds: 10
    - name: "task 3 play 3"
      pause:
        seconds: 10
    - debug:
        msg: "play 1 summary data:\ndata\ndata\ndata\ndata\ndata"
