--- 
- name: "my playbook"
  hosts: all
  
  tasks: 
    - name: "Print Job start"
      debug:
        msg: "Starting task. Pausing for 6 minutes..."
    - name: "Pause 6 minutes"
      pause:
        minutes: 6
    - name: "Print Task done"
      debug:
        msg: "Task DONE!!"
      